[build]
target = "avr-none"
rustflags = ["-C", "target-cpu=atmega2560"]

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"
runner = "ravedude"

[unstable]
build-std = ["core", "alloc"]
